name: CI

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - uses: actions/checkout@v4

      # Step 2: Checkout central actions repo
      # This is the key part — org is dynamic!
      - name: Checkout centralized actions repo
        uses: actions/checkout@v4
        with:
          repository: NareshSuresh/CentralizedRunners
          path: .github/actions/CentralizedRunners

      # Step 3: Use composite actions from the checked-out folder
      - name: Run Node Setup Action
        uses: ./.github/actions/CentralizedRunners/node-setup
        with:
          node-version: 20
