name: CI

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout centralized actions repo
        uses: actions/checkout@v4
        with:
          repository: NareshSuresh/CentralizedRunners
          ref: v0.3
          path: .github/actions/CentralizedRunners

      - name: Verify action folders
        run: ls -R .github/actions/CentralizedRunners

      - name: Run Node Setup Action
        uses: ./.github/actions/CentralizedRunners/node-setup
        with:
          node-version: 20

      - name: Run Python Setup Action
        uses: NareshSuresh/CentralizedRunners/python-setup@v0.3
        with:
          python-version: 3.10
